config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]

  namespace :admin do
    root to: "home#index" 
    resources :admins
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController <  AdminController

  def index
    @admins = Admin.order(id: :desc)
  end

  def new
  @admin = Admin.new
  end

  def create
    @admin = Admin.new(form_params)

    if @admin.save
      redirect_to admin_admins_path
    else
      render:new
    end
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update 
    @admin = Admin.find(params[:id])
    params = form_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params)
      redirect_to admin_admins_path
    else
      render :edit
    end
  end

  def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy
    redirect_to admin_admins_path
  end

  private  

  def form_params
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  layout 'admin/application'  

  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def authenticate_admin!
    redirect_to new_admin_session_path unless current_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path # ou a rota desejada para admins
    else
      super
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_form.html.erb
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body">
    <%= form_with(model: [:admin, admin], local: true) do |f| %>
      <%= render "layouts/form_errors", record: admin %>
      <div class="form-group">
        <label>Nome</label>
        <%= f.text_field :name, class: "form-control"%>
      </div>
      <div class="form-group">
        <label>Email</label>
        <%= f.email_field :email, class: "form-control"%>
      </div>
      <div class="form-row">
        <div class="col-6">
          <div class="form-group">
            <label>Senha</label>
            <%= f.password_field :password, class: "form-control"%>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <label for="exampleInputPassword1">Confirmar Senha</label>
            <%= f.password_field :password_confirmation, class: "form-control"%>
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Salvar</button>
      <%= link_to "Voltar", admin_admins_path, class: "btn btn-secondary ml-3" %>
    <% end %>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h2> Editar Administrador #<%= @admin.id %></h2>

<%= render "form", admin: @admin %>

app/views/admin/admins/index.html.erb
<%= link_to("Novo Administrador", new_admin_admin_path, class: "btn btn-success mb-4")%>

<h4>Admins</h4><br>

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">E-mail</th>
      <th scope="col">Criado em</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
    <tr>
      <th scope="row"><%= admin.id %></th>
      <td><%= admin.name %></td>
      <td><%= admin.email %></td>
      <td><%= admin.created_at %></td>
      <td><%= link_to "Editar", edit_admin_admin_path(admin), class: "btn btn-warning btn-sm" %></td>
      <td><%= link_to "Deletar", admin_admin_path(admin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %></td>
    </tr>
    <%
        end
    %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h2> Novo Administrador </h2>

<%= render "form", admin: @admin %>

app/views/admin/home/index.html.erb
<h2> Seja bem vindo ao painel admistrativo </h2>

app/views/layouts/_form_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= t('.error_on_save') %></h4>
    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path) ? 'active' : '' %>">
        <%= link_to("Home", admin_root_path, class: "nav-link" ) %>
      </li>
      <li class="nav-item <%= current_page?(admin_admins_path) ? 'active' : '' %>">
        <%= link_to("Administradores", admin_admins_path, class: "nav-link" ) %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Usuários</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Posts</a>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;">email@email.com</div>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", destroy_admin_session_path, method: :delete, class: "nav-link", data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Networking" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %> 

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "admin", media: "all", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "rails-ujs" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="height:100%;">
    <% if controller.controller_path.starts_with?('admin') %>
      <%= render 'layouts/admin/header' %> 
    <% end %>

    <%= content_for?(:content) ? yield(:content) : yield %> 
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Social Networking" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "rails-ujs" %>
  </head>

  <body style="height:100%;">
    <% if controller.controller_path.starts_with?('admin') %>
      <%= render 'layouts/admin/header' %> 
    <% end %>

    <%= content_for?(:content) ? yield(:content) : yield %> 
  </body>
</html>